name: Docker Image CI

on:
  workflow_dispatch:
  push:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}
      
        
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --tag aothen/ddddocr-fastapi:latest --platform linux/amd64 --push 
      
    - name: Setup SlimToolkit
      run: |
        curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
          
    - name: slim
      run: slim build  ddddocr-fastapi:latest --tag ddddocr-fastapi:slim
 

    - name: Push Docker image
      run: docker push aothen/ddddocr-fastapi:slim
