name: Docker Image CI

on:
  workflow_dispatch:

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
        
    - name: Build the Docker image
      run: docker buildx build . --file Dockerfile --tag ddddocr-fastapi:latest --platform linux/amd64
      
    - name: Setup SlimToolkit
      run: |
        curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
          
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

    - name: Push Docker image
      run: |
          slim build --http-probe=true --expose=8000 ddddocr-fastapi:latest
          docker push aothen/ddddocr-fastapi:latest
