name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      dockertag:
        required: false
        type: string
        default: 'latest'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: docker tag
      run:  echo ${{ inputs.dockertag }}


    # Build the Docker image first
    - uses: docker/build-push-action@v6
      with:
        push: false
        tags: ddddocr-fastapi:latest

    # Slim the Image
    - uses: kitabisa/docker-slim-action@v1.1.2
      env:
        DSLIM_HTTP_PROBE: false
      with:
        target: ddddocr-fastapi:latest
        tag: "slim-latest"

    # Docker Hub Login
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USER }}
        password: ${{ secrets.DOCKER_HUB_PWD }}

    # Push to the registry
    - name: Push Docker image
      run: | 
        docker tag ddddocr-fastapi:slim-latest ${{ secrets.DOCKER_HUB_USER }}/ddddocr-fastapi:slim-latest
        docker push ${{ secrets.DOCKER_HUB_USER }}/ddddocr-fastapi:slim-latest

    # - name: Set up QEMU
    #   uses: docker/setup-qemu-action@v3

    # - name: Setup Docker buildx
    #   uses: docker/setup-buildx-action@v3

    # - name: Login to Docker Hub
    #   uses: docker/login-action@v3
    #   with:
    #       username: ${{ secrets.DOCKER_HUB_USER }}
    #       password: ${{ secrets.DOCKER_HUB_PWD }}
      
        
    # - name: Build the Docker image
    #   run: docker build . --file Dockerfile --tag ddddocr-fastapi:latest
        
# docker buildx build . --file Dockerfile --tag aothen/ddddocr-fastapi:latest --platform linux/amd64 --push 
      
    # - name: Setup SlimToolkit
    #   run: |
    #     curl -sL https://raw.githubusercontent.com/slimtoolkit/slim/master/scripts/install-slim.sh | sudo -E bash -
          
    # - name: Slim docker
    #   run: slim build  ddddocr-fastapi:latest --tag ddddocr-fastapi:slim
 

    # - name: Push Docker image
    #   run: docker push aothen/ddddocr-fastapi:slim
